service: aws-node-lambda
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs16.x

functions:
  getAll:
    handler: handler.getAll
    events:
      - http: 
          path: posts
          method: get
          cors: true
