service: aws-node-lambda
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs16.x

functions:
  getAll:
    handler: handler.getAll
    events:
      - http: 
          path: posts
          method: get
          cors: true
  getOne:
    handler: handler.getOne
    events:
      - http: 
          path: posts/{id}
          method: get
          cors: true

plugins:
- serverless-auto-swagger
- serverless-offline # adding the plugin to be able to run the offline emulation
